name: Build and push Docker Image
#Test Docker
env:
  AWS_REGION_NAME      : "eu-central-1"
on: [push]


jobs:

  docker:
   runs-on: ubuntu-latest
   steps:
    -
     name: Checkout
     uses: actions/checkout@v2
    -
     name: Set up QEMU
     uses: docker/setup-qemu-action@v1
    -
     name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v1
    -
     name: Login to DockerHub
     uses: docker/login-action@v1
     with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.MYDOCKERTOKEN }}
    -
     name: Build and push
     uses: docker/build-push-action@v2
     with:
      context: .
      push: true
      tags: sedrikkh/node-web-app:latest
    -
     name: Configure my AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id      : ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key  : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region             : ${{env.AWS_REGION_NAME }}
    -
     name: AWS kubectl 
     run :
       aws eks --region eu-central-1 update-kubeconfig --name Adam_for_BTT_Cloud
    
    -   
     name:  Update deployment
     run : 
       kubectl set image deployment/adam-dep adam-app=sedrikkh/node-web-app:latest --record
   


